### ISSUE TITLE
Issues (?) with zip file

### ISSUE THREAD

**Issue by jkrehm** [resthub/resthub-backbone-stack#117]
The zip file referenced at [http://resthub.org/backbone-stack.html](http://resthub.org/backbone-stack.html) ([https://github.com/resthub/resthub-backbone-stack/downloads](https://github.com/resthub/resthub-backbone-stack/downloads)) has issues, likely by design. The main page (index.html) references "tests", but that directory is not included with the zip, so it 404's. I thought it was meant to be used via the router, but the route's name is "test" not "tests", so the link doesn't go to that, either. Is that intentional? If so, okay, but I found it confusing and had to do some debugging immediately after downloading it.

**Comment by bclozel** [comment]
I don't think it's intentional.
We removed the tests directory for that release, but we didn't update the index file.

Github has deprecated the download section, so we should in fact delete that file and update the main documentation. You just downloaded the 2.0 version, when the [2.1 version is already available](https://github.com/resthub/resthub-backbone-stack/archive/resthub-2.1.0.zip).

RESThub developers and users:
Should we use the native github feature with our SCM tags, or should we consider a binary repository like bintray.com ?

**Comment by jkrehm** [comment]
Thanks for the speedy response. I'll have to check out the 2.1 version soon.

**Comment by bmeurant** [comment]
keep using native github feature with SCM tags
