### ISSUE TITLE
[Backbone-validation] endless loop on flatten method

### ISSUE THREAD

**Issue by jycamier** [resthub/resthub-backbone-stack#130]
In case of reverse relation, there is an endless loop on flatten method.

The method getAttrsThatAreValidated() filtered the useless attributes for validation (including reverse relations).

**Comment by sdeleuze** [comment]
I rollback https://github.com/thedersen/backbone.validation/pull/133 because it caused our unit tests to fail.

2 solutions :
- We fix https://github.com/thedersen/backbone.validation/pull/133 in order to avoid RESThub stack test failure
- We find a better way to fix this bug

I won't be available this afternoon, so please see if @bmeurant could help you to fix this one
